stages:
  - build
  - publish 

build-vm:
  stage: build
  script:
    - packer build -var " " raspberryDesktop-stretch-vbox.json -except=vagrant,vagrant-cloud
  tags:
    - vagrant
  only:
    - master

publish-vm:
  stage: publish
  script:
    - packer build -var "version=$CI_COMMIT_TAG" raspberryDesktop-stretch-vbox.json
  tags:
    - vagrant
  only:
    - tags
