variables:
  GIT_STRATEGY: clone

stages:
  - build
  - publish 

build-vm:
  stage: build
  script:
    - packer build -var "version=  " -except="vagrant,vagrant-cloud" raspberryDesktop-stretch-vbox.json
  tags:
    - vagrant
  only:
    - master

publish-vm:
  stage: publish
  script:
    - packer build -var "version=$CI_COMMIT_TAG" raspberryDesktop-stretch-vbox.json
  tags:
    - vagrant
  only:
    - tags
